### ISSUE TITLE
Broken in newer versions of Flask (due to changes in Werkzeug)

### ISSUE THREAD

**Issue by mzpqnxow** [bluele/Flask-request-params#11]
```
    @property
    def json(self) -> t.Optional[t.Any]:
        """The parsed JSON data if :attr:`mimetype` indicates JSON
        (:mimetype:`application/json`, see :attr:`is_json`).

        Calls :meth:`get_json` with default arguments.

        If the request content type is not ``application/json``, this
        will raise a 400 Bad Request error.

        .. versionchanged:: 2.1
            Raise a 400 error if the content type is incorrect.     <-------- THIS IS A PROBLEM
        """
        return self.get_json()
 ```
 
 As of Werkzeug 2.1, using flask-request-params causes _all_ requests to fail (assuming you have something like `app.before_request(bind_request_params)` unless the content-type is `application/json`
 
 Seems that the fix for this will be a slight change to either have something like this:
 
 
 ```
 class Params(dict):

    def __init__(self, base_params=None, is_parse=True):
        self._params = base_params or {}
        logger.info("%s", base_params)
        logger.info("%s", dir(request))
        if is_parse:
            self.__assign_get_args(request.args)
            if request.view_args is not None:
                self.__assign_args(request.view_args)
            if request.json:                                                        <---- This is what triggers the failure
                self.__assign_args(request.json)
            else:
                if request.files:
                    self.__assign_args(request.files)
                self.__assign_body(request.form.items(multi=True))
```
 
 It seems that flask-request-params will need a change to more carefully inspect the request
 
 
 The exception looks like this:
 
 ```
 Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/venv/lib/python3.9/site-packages/flask_request_params/params.py", line 111, in bind_request_params
    setattr(request, attr_name, get_request_params())
  File "/venv/lib/python3.9/site-packages/flask_request_params/params.py", line 106, in get_request_params
    setattr(request, '_request_params', Params(base_params))
  File "/venv/lib/python3.9/site-packages/flask_request_params/params.py", line 16, in __init__
    if request.json:
  File "/venv/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 540, in json
    return self.get_json()
  File "/venv/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 587, in get_json
    rv = self.on_json_loading_failed(e)
  File "/venv/lib/python3.9/site-packages/flask/wrappers.py", line 128, in on_json_loading_failed
    return super().on_json_loading_failed(e)
  File "/venv/lib/python3.9/site-packages/werkzeug/wrappers/request.py", line 609, in on_json_loading_failed
    raise BadRequest(f"Failed to decode JSON object: {e}")
```

**Comment by mzpqnxow** [comment]
At the very least, there should probably be a `werkzeug<2.1` in the `setup.cfg` so users don't run into this. I'll try to figure out the simplest and most practical way to fix this and send a PR if I have a chance. I really like using flask-request-params, so thanks for your effort on the project

**Comment by mzpqnxow** [comment]
One option is to guard access to the `Request.json` property within `flask-request-params`, like this:


```python
    def __init__(self, base_params=None, is_parse=True):
        self._params = base_params or {}
        if is_parse:
            self.__assign_get_args(request.args)
            if request.view_args is not None:
                self.__assign_args(request.view_args)
            if request.mimetype == 'application/json' and request.json:
                self.__assign_args(request.json)
            else:
                if request.files:
                    self.__assign_args(request.files)
                self.__assign_body(request.form.items(multi=True))
```
